### ISSUE TITLE
Nodata is being set to the wrong value

### ISSUE THREAD

**Issue by alexgleith** [digitalearthpacific/dep-mangroves#6]
For the `mangroves`, `closed` and `regular` bands, nodata is set on the COG as `-32767` but in the data it is `0`.

Please ensure that we use the correct nodata value setting on the COGs, so that it's respected in desktop apps.

**Comment by sopac** [comment]
.where(lambda x: x > 0, other=np.nan)  # sentinel-2 uses 0 as nodata

**Comment by jessjaco** [comment]
As noted in slack, 0 = no mangroves, not nodata. We could revisit this though, so tabling for now

**Comment by alexgleith** [comment]
How do we intend this data to be used/visualised?

If we don't make the `0` nodata, then we end up with a huge grey area.

Aren't we limiting our potential mangrove regions to the GMW extent? If so, then outside that extent it should be `nodata`. So then inside it's `mangrove/closed/regular`...

Image below is showing `mangrove/closed/regular` on RGB and without setting `0` as nodata.

<img width="1478" alt="image" src="https://github.com/digitalearthpacific/dep-mangroves/assets/3445853/0e3eb67c-813b-4c80-9c52-b1c6e1c0ac7e">

**Comment by alexgleith** [comment]
I think this is fixed.
