### ISSUE TITLE
Should we combine `mangroves`, `closed` and `open` in a single .tif

### ISSUE THREAD

**Issue by alexgleith** [digitalearthpacific/dep-mangroves#7]
Many remote sensing products use a bitmask to encode multiple categorical values into a single band, i.e., [DEA WOfS](https://cmi.ga.gov.au/data-products/dea/613/dea-water-observations-landsat#details) or the Landsat `qa_pixel`.

If we use a bitmask where we set the following:

* `0`: `nodata`
* `1`: `mangroves`
* `2`: `closed`
* `3`: `regular`

Then it is simple to display all the different combinations by loading a single 8-bit file, rather than three three ~`float32`~ 16 bit int files we are currently using for storage.

**Comment by jessjaco** [comment]
Mangroves is either closed or regular, so there would be no 1 value under this schema. Maybe a bitmask?
00000000 = 0 = no mangroves
00000010 = 2 = regular
00000011 = 3 = closed

Then e.g. bitwise <value> & 2 would code to mangrove, etc

**Comment by alexgleith** [comment]
That's what I mean, sorry. Using a bit mask.

Pretty easy to untangle using a colourmap...

**Comment by alexgleith** [comment]
This has been done.
