### ISSUE TITLE
STAC documents aren't properly formatted

### ISSUE THREAD

**Issue by alexgleith** [digitalearthpacific/dep-mangroves#8]
For example, [this document](https://deppcpublicstorage.blob.core.windows.net/output/dep_s2_mangroves/0-0-2/PG/019/2022/dep_s2_mangroves_PG_019_2022.stac-item.json)

Throws a validation error: `ValidationError: '2022-01-01T00:00:00.000' does not match '(\\+00:00|Z)$'`

And it doesn't have `collection` field included. [WOfS does.](https://deppcpublicstorage.blob.core.windows.net/output/dep_ls_wofs/0-0-3/GU/002/2019/dep_ls_wofs_GU_002_2019_mean.stac-item.json)

According to the [spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md)

>This field is required if such a relation type is present

**Comment by jessjaco** [comment]
Should be fixed by https://github.com/digitalearthpacific/dep-tools/commit/cc16986fce69079954b0aed1deb6dab0b7c873c7

**Comment by jessjaco** [comment]
See https://deppcpublicstorage.blob.core.windows.net/output/dep_s2_mangroves/test-5/PG/011/2023/dep_s2_mangroves_PG_011_2023.stac-item.json for example, looks good to me

**Comment by alexgleith** [comment]
STAC docs are validating now. See the other related fix here though: https://github.com/digitalearthpacific/dep-tools/pull/14
